#ifndef _CONFIG_H_
#define _CONFIG_H_

#define TIMER_PERIOD 32
#define DEBOUNCE_PERIOD_MS 20
#define LONG_PRESS_PERIOD_MS 300

#define RAINBOW_PERIOD_MS 5000
#define COLOR_TRANSITION_PERIOD_MS 500
#define COLOR_SWAP_PERIOD_MS 5000

#define RAINBOW_BLEND_FACTOR 200

#endif