#ifndef _CONFIG_H_
#define _CONFIG_H_

#define ANIM_PERIOD_MS 3000

#define DEBOUNCE_TIME_MS 20
#define LONG_PRESS_TIME_MS 500

#define COLOR_TRANSITION_TIME_MS 500

#define RAINBOW_BLEND_FACTOR 200
#define RANDOM_BLEND_FACTOR 50

#define TIMER_PERIOD 32
#define ANIMATION_DELTA ((ANIM_PERIOD_MS * 1000UL) / TIMER_PERIOD)
#define DEBOUNCE_DELTA ((DEBOUNCE_TIME_MS * 1000UL) / TIMER_PERIOD)
#define LONG_PRESS_DELTA ((LONG_PRESS_TIME_MS * 1000UL) / TIMER_PERIOD)
#define TRANSITION_DELTA ((COLOR_TRANSITION_TIME_MS * 1000UL) / TIMER_PERIOD)

#ifndef F_CPU
#define F_CPU 16000000
#endif

#endif